name: CI Pipeline

on:
  pull_request:
    branches: [ stage ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-

    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test -- --watchAll=false
